encoder: Fix compile warnings due to unhandled enumeration values in a switch statement.
$HEVC/source/encoder/encoder.cpp: In member function ???void x265::Encoder::determineLevelAndProfile(x265_param_t*)???:
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value ???NONE??? not handled in switch [-Werror=switch]
     switch (m_level)
            ^
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value ???LEVEL1??? not handled in switch [-Werror=switch]
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value ???LEVEL2??? not handled in switch [-Werror=switch]
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value ???LEVEL2_1??? not handled in switch [-Werror=switch]
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value ???LEVEL3??? not handled in switch [-Werror=switch]
$HEVC/source/encoder/encoder.cpp:119:12: error: enumeration value ???LEVEL3_1??? not handled in switch [-Werror=switch]
cc1plus: all warnings being treated as errors